import type { FabbleMode } from "./types";

// ─── Set release order ────────────────────────────────────────────────────────
// 19 confirmed booster set codes in confirmed release order (Decision #3).
// Cards from set codes not in this list get earliestSetIndex = Infinity and
// emit a build-time warning. The 3-char prefix is extracted from setIdentifiers
// (e.g. "MST131" → "MST").
export const SET_ORDER: string[] = [
	"WTR", // Welcome to Rathe
	"ARC", // Arcane Rising
	"CRU", // Crucible of War
	"MON", // Monarch
	"ELE", // Tales of Aria
	"EVR", // Everfest
	"1HP", // History Pack 1
	"UPR", // Uprising
	"DYN", // Dynasty
	"OUT", // Outsiders
	"DTD", // Dusk till Dawn
	"EVO", // Bright Lights (Evo)
	"HVY", // Heavy Hitters
	"MST", // Part the Mistveil
	"ROS", // Rosetta
	"HNT", // The Hunted
	"SEA", // High Seas
	"SMP", // Super Slam
	"SUP", // Omens of the Third Age
];

// ─── Guess limits per mode ────────────────────────────────────────────────────
export const GUESS_LIMITS: Record<FabbleMode, number> = {
	standard: 8,
	chaos: 12,
};

// ─── Autocomplete ─────────────────────────────────────────────────────────────
export const AUTOCOMPLETE_MAX_RESULTS = 10;

// ─── Hint system ─────────────────────────────────────────────────────────────
// Standard mode only. Index 0 = guess count at which hint 1 unlocks, etc.
export const HINT_UNLOCK_THRESHOLDS: number[] = [3, 5];

// ─── Animation timing ─────────────────────────────────────────────────────────
// TILE_FLIP_DURATION_MS: duration of the tile flip animation (GuessGrid live text delay)
// POST_SOLVE_DELAY_MS: delay before post-solve panel appears (100ms after flip completes)
export const TILE_FLIP_DURATION_MS = 1300;
export const POST_SOLVE_DELAY_MS = 1400;

// ─── Selection thresholds ─────────────────────────────────────────────────────
// Minimum eligible pool size before suppression fallback kicks in
export const ELIGIBLE_POOL_MIN_SIZE = 10;

// ─── Type exclusions (applied in both Standard and Chaos filters) ─────────────
// These types are not "cards" in the deduction sense.
export const EXCLUDED_TYPES: Set<string> = new Set([
	"Token",
	"Mentor",
	"Resource",
	"Demi-Hero",
	"Macro",
	"Meld",
	"Event",
	"Block",
	"Companion",
]);

// ─── Suppression window ───────────────────────────────────────────────────────
// Cards recently chosen as dailies are suppressed for this many days.
export const SUPPRESSION_WINDOW = 90;

// ─── CDN base URL for card images ────────────────────────────────────────────
// Full URL = `${FAB_CDN_BASE}${defaultImage}.webp`
// Example: "https://content.fabrary.net/cards/MST131.webp"
export const FAB_CDN_BASE = "https://content.fabrary.net/cards/";

// ─── Set name → release order index ──────────────────────────────────────────
// Generated by scripts/generate-set-order.ts — edit data/set-release-order.csv
// and re-run the script instead of editing this block directly.
export const SET_NAME_TO_INDEX: Record<string, number> = {
	"Welcome to Rathe": 0, // 11/10/2019
	"Ira Welcome Deck": 1, // 11/10/2019
	"Bravo Demo Deck": 2, // 11/10/2019
	"Dorinthea Demo Deck": 3, // 11/10/2019
	"Bravo Hero Deck": 4, // 11/10/2019
	"Dorinthea Hero Deck": 5, // 11/10/2019
	"Rhinar Hero Deck": 6, // 11/10/2019
	"Katsu Hero Deck": 7, // 11/10/2019
	"Promos": 8, // 11/10/2019
	"Arcane Rising": 9, // 27/03/2020
	"Crucible of War": 10, // 02/10/2020
	"Monarch": 11, // 26/03/2021
	"Boltyn Blitz Deck": 12, // 07/05/2021
	"Chane Blitz Deck": 13, // 07/05/2021
	"Levia Blitz Deck": 14, // 07/05/2021
	"Prism Blitz Deck": 15, // 07/05/2021
	"Tales of Aria": 16, // 24/09/2021
	"Briar Blitz Deck": 17, // 24/09/2021
	"Katsu Blitz Deck": 18, // 24/09/2021
	"Lexi Blitz Deck": 19, // 24/09/2021
	"Oldhim Blitz Deck": 20, // 24/09/2021
	"Everfest": 21, // 28/01/2022
	"History Pack 1": 22, // 06/05/2022
	"Classic Battles: Rhinar vs Dorinthea": 23, // 27/05/2022
	"Uprising": 24, // 24/06/2022
	"Fai Blitz Deck": 25, // 24/06/2022
	"Dromai Blitz Deck": 26, // 24/06/2022
	"Verdance Blitz Deck": 27, // 24/06/2022
	"Dynasty": 28, // 07/10/2022
	"Nuu Blitz Deck": 29, // 24/03/2023
	"Uzuri Blitz Deck": 30, // 24/03/2023
	"Arakni Blitz Deck": 31, // 24/03/2023
	"Azalea Blitz Deck": 32, // 24/03/2023
	"Benji Blitz Deck": 33, // 24/03/2023
	"Riptide Blitz Deck": 34, // 24/03/2023
	"Outsiders": 35, // 14/04/2023
	"Dusk till Dawn": 36, // 21/07/2023
	"Round the Table: TCC x LSS": 37, // 29/09/2023
	"Bright Lights": 38, // 06/10/2023
	"Kassai Blitz Deck": 39, // 02/02/2024
	"Betsy Blitz Deck": 40, // 02/02/2024
	"Olympia Blitz Deck": 41, // 02/02/2024
	"Victor Blitz Deck": 42, // 02/02/2024
	"Rhinar Blitz Deck": 43, // 02/02/2024
	"Kayo Blitz Deck": 44, // 27/02/2024
	"Heavy Hitters": 45, // 08/03/2024
	"Armory Deck: Kayo": 46, // 03/05/2024
	"Enigma Blitz Deck": 47, // 31/05/2024
	"Zen Blitz Deck": 48, // 31/05/2024
	"Part the Mistveil": 49, // 05/07/2024
	"Armory Deck: Boltyn": 50, // 12/07/2024
	"Armory Deck: Azalea": 51, // 02/08/2024
	"1st Strike: Aurora": 52, // 23/08/2024
	"1st Strike: Terra": 53, // 23/08/2024
	"Florian Blitz Deck": 54, // 20/09/2024
	"Oscilio Blitz Deck": 55, // 20/09/2024
	"Aurora Blitz Deck": 56, // 20/09/2024
	"Rosetta": 57, // 04/10/2024
	"Armory Deck: Dash": 58, // 18/10/2024
	"Armory Deck Origins: Jarl": 59, // 29/11/2024
	"Cindra Blitz Deck": 60, // 31/01/2025
	"Arakni Hunted Blitz Deck": 61, // 31/01/2025
	"Arakni, Web of Deceit Blitz Deck": 62, // 31/01/2025
	"Fang Blitz Deck": 63, // 31/01/2025
	"GEM": 64, // 01/02/2025
	"The Hunted": 65, // 07/03/2025
	"Armory Deck: Maxx": 66, // 17/04/2025
	"Armory Deck: Gravy Bones": 67, // 30/05/2025
	"High Seas": 68, // 04/07/2025
	"Super Slam": 69, // 04/07/2025
	"Armory Deck: Ira": 70, // 11/07/2025
	"Armory Deck Legends: Viserai": 71, // 24/07/2025
	"Armory Deck Legends: Prism": 72, // 31/07/2025
	"Mastery Pack: Guardian": 73, // 08/08/2025
	"Smash Palace": 74, // 29/08/2025
	"Armory Deck: Pleiades": 75, // 19/09/2025
	"Armory Deck: Rhinar": 76, // 14/11/2025
	"Armory Deck: Arakni": 77, // 12/12/2025
	"Tournament Pack": 78, // 13/02/2026
	"Compendium of Rathe": 79, // 13/02/2026
	"Arakni Silver Age Deck": 80, // 13/02/2026
	"Azalea Silver Age Deck": 81, // 13/02/2026
	"Bravo Silver Age Deck": 82, // 13/02/2026
	"Dash Silver Age Deck": 83, // 13/02/2026
	"Dorinthea Silver Age Deck": 84, // 13/02/2026
	"Enigma Silver Age Deck": 85, // 13/02/2026
	"Fai Silver Age Deck": 86, // 13/02/2026
	"Iyslander Silver Age Deck": 87, // 13/02/2026
	"Kayo Silver Age Deck": 88, // 13/02/2026
	"Viserai Silver Age Deck": 89, // 13/02/2026
	"Armory Deck Origins: Hala": 90, // 17/04/2026
	"Armory Deck: Zyggy": 91, // 29/05/2026
	"Boltyn Silver Age Deck": 92, // 05/06/2026
	"Briar Silver Age Deck": 93, // 05/06/2026
	"Blaze Silver Age Deck": 94, // 05/06/2026
	"Gravy Bones Silver Age Deck": 95, // 05/06/2026
	"Lyath Silver Age Deck": 96, // 05/06/2026
	"Omens of the Third Age": 97, // 05/06/2026
	"Mastery Pack: Warrior": 98, // 07/08/2026
	"Armory Deck: Olympia": 99, // 07/08/2026
};
