blank_issues_enabled: false
contact_links:
    - name: Questions & Discussions
      url: https://github.com/FABKIT/FABKIT/discussions
      about: Use GitHub discussions for message-board style questions, discussions and feature requests

    - name: Support development
      url: https://ko-fi.com/fabkit
      about: If you want to support the development, check out our Ko-Fi
