import type { FabbleCardType } from "@fabkit/apps/fabble/types";
import { COLUMNS } from "@fabkit/apps/fabble/types";

export const FABBLE_DATA_URL = import.meta.env.DEV
	? "/fabble-sample-data.json"
	: "https://fabkit.github.io/fabble-data/v1/dataset.json";
// ^ THE swap point: dev uses the hand-authored fixture; production fetches
// the real feed generated by github.com/FABKIT/fabble-admin.

export const MODES = ["standard", "chaos"] as const;
export type FabbleMode = (typeof MODES)[number];
export const MAX_GUESSES: Record<FabbleMode, number> = {
	standard: 8,
	chaos: 12,
};
export const HINT_UNLOCK_GUESSES = [3, 5] as const;
export const ELIGIBLE_TYPES: FabbleCardType[] = [
	"hero",
	"weapon",
	"equipment",
	"action",
	"attack_action",
	"attack_reaction",
	"defense_reaction",
	"instant",
	"ally",
]; // display order of the chips row (spec §4.3); labels via fabble i18n keys
export const MAX_SEARCH_RESULTS = 10;
export const USERNAME_MAX_LENGTH = 20;
export const SHARE_LINK = "https://fabkit.io/fabble";

/** Tile reveal timing — single source of truth shared by FeedbackBlock (per-tile
    animationDelay) and EndPanel (wait before fading in). Derived, never hardcoded:
    stays correct if COLUMNS or the stagger/flip durations ever change. */
export const TILE_STAGGER_MS = 80;
export const TILE_FLIP_MS = 500; // must equal the fabble-flip duration in fabble.css
export const REVEAL_TOTAL_MS =
	(COLUMNS.length - 1) * TILE_STAGGER_MS + TILE_FLIP_MS;
